import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import SideBar from '@/Components/SideBar/SideBar'
import Main from '@/Components/Main/Main'
import { useSelector } from 'react-redux'
import { RootState } from 'store'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const bgColor = useSelector((state: RootState) => state.bgcolor.value)
  const fontColor = useSelector((state: RootState) => state.fontColor.value)

  return (
    <div className={styles.container} style={{backgroundColor: bgColor,color: fontColor}}>
       <Head>
        <title>Calci Pay App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='./logo.png' />
      </Head>
      <SideBar />
      <Main text={'Enter the amount that you are planning to pay Monthly and let Calci App do the calculations for you!'} />
    </div>
  )
}
